### ISSUE TITLE
BUG: Wrong layout in execution editor

### ISSUE THREAD

**Issue by PhilipVinc** [Ecpy/ecpy#24] opened 2016-01-22 17:20 UTC
Add two random tasks, then go to the execution editor panel, and try to tick the checkboxes for "stoppable" and "Parallel" and/or "Wait. 
You wil see that the nesting is wrong

**Comment by MatthieuDartiailh** [comment] 2016-01-24 19:37
I cannot reproduce that.

**Comment by PhilipVinc** [comment] 2016-01-24 21:09
Maybe I was not completely clear? That is what I meant
![bb](https://cloud.githubusercontent.com/assets/2407108/12538936/23205710-c2e7-11e5-99bf-1c9d05ae33b5.jpg)

**Comment by MatthieuDartiailh** [comment] 2016-01-24 21:19
I think I fixed this in my last commit. It was a spacing issue. Could you check again ?

**Comment by PhilipVinc** [comment] 2016-01-24 22:19
Yes, It's now fixed.

**Comment by MatthieuDartiailh** [comment] 2016-01-25 05:58
Closing hence.

**Closed by MatthieuDartiailh** 2016-01-25 05:58 UTC
